### ISSUE TITLE
CSS problem: rdw-option-wrapper's height should be 30px

### ISSUE THREAD

**Issue by ZeroCho** [jpuri/react-draft-wysiwyg#123]
I think rdw-option-wrapper's height should be 30px to be aligned with rdw-dropdown-wrapper.

**Comment by ZeroCho** [comment]
Oh, I found why my editor's basic style looks different from yours. It's because I use `box-sizing: border-box`

I think it will be better if you add `box-sizing: content-box` or `box-sizing: border-box` at the root of the editor for clearity.

**Comment by jpuri** [comment]
I will check this out @ZeroCho, thanks for nice suggestion.

**Comment by jpuri** [comment]
Fixed.

**Comment by mbrnwsk** [comment]
The issue still exists - there is a conflict if we have `box-sizing: border-box` applied to all elements globally (this is what normalizr.css does); react-draft-wysiwyg.css uses `box-sizing: content-box` which causes inconsistencies. Since a lot of users use normalizr I would suggest to switch to `border-box` in rdw.

**Comment by jpuri** [comment]
I will look into this @mbrnwsk

**Comment by ZeroCho** [comment]
yes. I also use box-sizing: border-box globally and it conflicts with rdw
