### ISSUE TITLE
Ability to remove icon that appears over link on hover

### ISSUE THREAD

**Issue by jdpagley** [jpuri/react-draft-wysiwyg#161]
Seems like it's opinionated to have an icon appear on hover. I think most people would expect the traditional link instead of that additional functionality on hover.

**Comment by jpuri** [comment]
Agree with you @jdpagley, I will make it configurable using properties.

**Comment by jdpagley** [comment]
@jpuri thank you so much!

**Comment by chetanmotamarri** [comment]
@jpuri Is there any option to hide icon on hover ?

**Comment by jpuri** [comment]
Hey @chetanmotamarri : you can use this option: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/config/defaultToolbar.js#L107

**Comment by chetanmotamarri** [comment]
It's not working, icon is shown even when I gave 'showOpenOptionOnHover: false', could you please check once.

**Comment by jpuri** [comment]
Yep checking this.

**Comment by jpuri** [comment]
@chetanmotamarri: Your are right this feature is broken I just checked. An ugly hack you can use for now is:

```
.rdw-link-decorator-icon {
  display: none;
}
```

I will soon fix the issue.

**Comment by chetanmotamarri** [comment]
Thank you,

**Comment by jpuri** [comment]
Issue is fixed in release: `react-draft-wysiwyg@1.9.8`.

**Comment by Serse2** [comment]
hiii,
if i set the link option:  showOpenOptionOnHover: false 
there are no possibility to open the link, there are any ways to open the link without icon?
thaks 

nice library

**Comment by fabiojsousa** [comment]
I still have this problem on  the version `^1.14.7`. The only way so far to work aroud this problem I've found is:

```
img.rdw-link-decorator-link {
    display: none;
  }
```

**Comment by glenn-agaetis** [comment]
How can i add my own styling here ?
