### ISSUE TITLE
textAlign is not restored

### ISSUE THREAD

**Issue by sylvainbx** [jpuri/react-draft-wysiwyg#286]
When initializing the Editor with some previously saved content, eg:
```json
{"blocks":[
  {"key":"78mel",
  "text":"Lorem ipsum duis vulputate erat vel tortor ornare lobortis. In tempus aliquet elit nec porttitor.",
  "type":"unstyled",
  "depth":0,
  "inlineStyleRanges":[],
  "entityRanges":[],
  "data":{"textAlign":"center"}}
],"entityMap":{}}
```
The text alignment is not restored. All other properties are restored correctly (bold, italic, list ...), but textAlign (here `center` but possibly `right` or `justify`) are not restored.

Here's the peace of code I use to load the initial content:
```jsx
  constructor(props) {
    super(props);
    this.state = {
      editorState: TextEditor.initialState(props.rawState),
    };
  }
  (...)
  static initialState(rawState) {
    if (rawState) {
      if (!rawState.entityMap) { rawState.entityMap = {}; }
      const contentState = convertFromRaw(rawState);
      return EditorState.createWithContent(contentState);
    }
    return EditorState.createEmpty();
  }

  render() {
    const { editorState } = this.state;
    const { placeholder } = this.props;
    return (
      <div className="m-t-md">
        <Editor editorState={editorState}
                toolbarClassName="text-editor__toolbar"
                wrapperClassName="text-editor__wrapper"
                editorClassName="text-editor__editor"
                onEditorStateChange={this.onEditorStateChange.bind(this)}
                placeholder={placeholder}
                toolbar={this.toolbar} />
      </div>
    );
  }
```
Any suggestion is welcome :)

**Comment by jpuri** [comment]
@sylvainbx : thanks for reporting the issue, I will check this.

**Comment by jpuri** [comment]
Also, @sylvainbx : are you facing this issue when you display content in HTML ? That I fixed in last version already.

**Comment by sylvainbx** [comment]
Hi, thanks for your answer. I've just upgraded react-draft-wysiwyg from 1.9.0 to 1.9.4 but sadly, this does not solve the issue.

I don't know what you mean by "display content in HTML". I'm displaying some draft raw content in the `<Editor />`, using `convertFromRaw` and `createWithContent`.

**Comment by jpuri** [comment]
This should be fixed in latest version, can you plz check: `react-draft-wysiwyg@1.9.7`.

**Comment by cesaracortes** [comment]
Hi! 
I have the same problem, and im using the version react-draft-wysiwyg@1.9.7

**Comment by jpuri** [comment]
I will check this again. Thanks for reporting @cesaracortes

**Comment by sylvainbx** [comment]
Hi, I've upgraded to react-draft-wysiwyg@1.9.8, but I still have the issue.
Moreover, now I'm having the following error in the console:

```console
warning.js?85a7:36 Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types
    in e (created by TextEditor)
    in TextEditor (created by ProjectId)
    ...
```

**Comment by adashst** [comment]
Same for me.

When trying to load :
```
const contentBlocks = convertFromHTML('<p style="text-align:right;">right aligned</p>')
const editorState = EditorState.createWithContent(ContentState.createFromBlockArray(contentBlocks))
```
style seems to be stripped out. 

editorState is:
``` {
        entityMap: {},
        blockMap: {
          '89ct4': {
            key: '89ct4',
            type: 'unstyled',
            text: 'right aligned',
            characterList: [
              { style: [], entity: null },
              { style: [], entity: null },
              { style: [], entity: null },
              { style: [], entity: null },
              { style: [], entity: null },
              { style: [], entity: null },
              { style: [], entity: null },
              { style: [], entity: null },
              { style: [], entity: null },
              { style: [], entity: null },
              { style: [], entity: null },
              { style: [], entity: null },
              { style: [], entity: null },
            ],
            depth: 0,
            data: {},
          },
        },
        selectionBefore: {
          anchorKey: '89ct4',
          anchorOffset: 0,
          focusKey: '89ct4',
          focusOffset: 0,
          isBackward: false,
          hasFocus: false,
        },
        selectionAfter: {
          anchorKey: '89ct4',
          anchorOffset: 0,
          focusKey: '89ct4',
          focusOffset: 0,
          isBackward: false,
          hasFocus: false,
        },
      }
```

I guess `data: {}` should be: `data: {'text-align': 'right'}` after `convertFromHTML`.
Maybe i'm doing sth wrong?

I'm using 
- draft-js 0.10.1
- draftjs-to-html 0.7.2
- react-draft-wysiwyg 1.9.8

**Comment by sylvainbx** [comment]
Any update on this ?

**Comment by thuanhd** [comment]
Me too, get a trouble with text-align when convertFromHtml. Any help?

**Comment by ed-zm** [comment]
I am running into the same issue, any update for this?

**Comment by luqezman** [comment]
Any updates? I'm having this problem :(

**Comment by Slooowpoke** [comment]
I was having the same issue using the default convertFromHTML (from Draft.js), but after switching to the recommended package: https://github.com/jpuri/html-to-draftjs and using ```htmlToDraft``` instead solved my issue.

**Comment by jpuri** [comment]
This is working well here in storybook: https://github.com/jpuri/react-draft-wysiwyg/blob/master/stories/ConvertFromRawDraftContent/index.js#L19

**Comment by shanmuga2414** [comment]
i want to send these editorState content  send to as a email to Gmail. How to handle this editorstate content using Node JS

**Comment by suvomoy** [comment]
Same problem here when rendering editorState :
```
const contentDataState =
        ContentState.createFromBlockArray(convertFromHTML("<h3 style="text-align:center;"><span style="font-family: Tahoma;"><strong>This A Sample Text</strong></span></h3>"));
const [editorState, seteditorState] = React.useState(EditorState.createWithContent(contentDataState));
```
I'm using:
"react-draft-wysiwyg": "^1.14.7"
"draft-js": "^0.11.7",
 "draftjs-to-html": "^0.9.1",

**Comment by SaundersB** [comment]
Same issue here:

`<p style="text-align:right;"><strong>It’s different, but we like different.</strong></p>`


```
const blocksFromHtml = convertFromHTML(defaultValue);
        const contentState = ContentState.createFromBlockArray(
          blocksFromHtml.contentBlocks,
          blocksFromHtml.entityMap
        );
        const newEditorState = EditorState.createWithContent(contentState);
        setEditorState(newEditorState);

...

return (<Editor
        toolbarHidden
        readOnly={true}
        editorState={editorState}
        onEditorStateChange={onEditorStateChange}
      />);
```

    "react-draft-wysiwyg": "^1.15.0",
 "draft-js": "^0.11.7",
    "draftjs-to-html": "^0.9.1",
